### ISSUE TITLE
Add cesium_view for all resources of a dataset search result

### ISSUE THREAD

**Issue by florianm** [datagovau/ckanext-cesiumpreview#3]
On the `/dataset` page, add a "Map all the things" button which opens NationalMap full-screen in a new tab with all spatial resources of datasets shown.

If that works on the result of a dataset search, it would also work on an unfiltered list of all datasets, both through GUI and API.

Discussion points:
- The list of datasets could span several pages of results. Before a search this list would be all contained datasets. The number of datasets needs an upper limit.
- Displaying a heap of datasets might be tricky. Group them by CKAN orgs or groups maybe? Or both in separate submenus?
- Datasets could have several spatial resources showing the same data (e.g. WMS and WFS, or shp, geojson, kml). Rendering WFS and WMS returns different things, rendering shp/gj/kml will look the same on NationalMap.
- Sending datasets to NationalMap via URL parameters will cap out at the 2000 character URL limit. So I assume the config needs to be sent via GET request dict.
- Resulting maps (= the NationalMap "share" URL) might be worth keeping as CKAN resource on a new dataset. Is there a way to shortcut this process? E.g. a new NationalMap menu item inside the "share" menu that opens a mini-CKAN-create-dataset-with-resource-URL-form, that posts back to CKAN if the user has create dataset permission?

**Comment by maxious** [comment]
NationalMap can load lists of datasets from CKAN via a single CKAN package_search call with whatever solr query you desire https://github.com/NICTA/nationalmap/blob/master/datasources/01_Data.gov.au.json

These can then be grouped by group or category https://github.com/TerriaJS/terriajs/blob/8edeb4047224c046705949753db596b373f02ed6/lib/Models/CkanCatalogGroup.js#L107

**Comment by florianm** [comment]
So IIUC if I could grab the search from the URL or somehow from the view controller that's all we need for a "view (spatial datasets included in) search result in NationalMap"?

**Comment by maxious** [comment]
Yeah, just put q= and fq= into the filterQuery config for NM.
eg. https://data.gov.au/dataset?q=ground&res_format=ZIP would be filterQuery="q=ground&fq=res_format:ZIP" 
Basically anything that isn't q/sort/page on the GET parameters is a fq value - you can copy this code to another plugin, the request object is global and has the parameters already parsed into a dict https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L211

**Comment by florianm** [comment]
@maxious I've had a go at the URL but I'll need your advice - can't seem to get the right format.

If I had a CKAN search like http://catalogue.beta.data.wa.gov.au/dataset?groups=habitat-sampling-initiative, what URL do I need to send to nationalmap to display all say geojson resources of my result set?

I've tried url-encoding this:
```
{
  "catalog": [
    {
      "groupBy": "organization",
      "minimumMaxScaleDenominator": 10000000000,
      "filterQuery": [
        "fq=+(res_format:geojson)"
      ],
      "url": "http://catalogue.beta.data.wa.gov.au",
      "type": "ckan",
      "name": "data.wa.gov.au"
    }
  ]
}
```
into https://nationalmap.gov.au/#clean&hideExplorerPanel=1&start=%7B%0A%20%20%22catalog%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22groupBy%22%3A%20%22organization%22%2C%0A%20%20%20%20%20%20%22minimumMaxScaleDenominator%22%3A%2010000000000%2C%0A%20%20%20%20%20%20%22filterQuery%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22fq%3D%2B(res_format%3Ageojson)%22%0A%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%22url%22%3A%20%22http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%22%2C%0A%20%20%20%20%20%20%22type%22%3A%20%22ckan%22%2C%0A%20%20%20%20%20%20%22name%22%3A%20%22data.wa.gov.au%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D
to no avail.
Would I need to just find the right combination of parameters, or what am I doing wrong?

**Comment by maxious** [comment]
There's a bit more boiler plate you need https://github.com/datagovau/ckanext-cesiumpreview/blob/master/ckanext/cesiumpreview/theme/public/preview_cesium.js#L10

https://nationalmap.gov.au/#clean&hideExplorerPanel=1&start=%7B%20%22version%22%3A%220.0.03%22%2C%20%22initSources%22%3A%5B%7B%20%22catalog%22%3A%5B%7B%20%22type%22%3A%22group%22%2C%20%22name%22%3A%22User-AddedData%22%2C%20%22description%22%3A%22ThegroupfordatathatwasaddedbytheuserviatheAddDatapanel.%22%2C%20%22isUserSupplied%22%3Atrue%2C%20%22isOpen%22%3Atrue%2C%20%22items%22%3A%5B%7B%22groupBy%22%3A%22organization%22%2C%22minimumMaxScaleDenominator%22%3A10000000000%2C%22filterQuery%22%3A%5B%22fq%3D%2B(res_format%3Ageojson)%22%5D%2C%22url%22%3A%22http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%22%2C%22type%22%3A%22ckan%22%2C%22name%22%3A%22data.wa.gov.au%22%7D%5D%20%7D%5D%2C%20%22catalogIsUserSupplied%22%3Atrue%2C%20%22homeCamera%22%3A%7B%20%22west%22%3A105%2C%20%22south%22%3A-45%2C%20%22east%22%3A155%2C%20%22north%22%3A-5%20%7D%20%20%7D%20%5D%20%20%7D

You also need CORS enabled on your server because there seems to be a bug adding double slashes after the domain name when using the proxy - https://nationalmap.gov.au/proxy/_1d/http://catalogue.beta.data.wa.gov.au//api/3/action/package_search?rows=100000&fq=+(res_format:geojson) doesn't work (404) while https://nationalmap.gov.au/proxy/_1d/http://catalogue.beta.data.wa.gov.au/api/3/action/package_search?rows=100000&fq=+(res_format:geojson) at least returns 0 results

Recent versions of CKAN includes CORS settings in app config http://docs.ckan.org/en/latest/maintaining/configuration.html?highlight=cors#cors-settings else can configure Apache/Nginx http://enable-cors.org/server.html

**Comment by florianm** [comment]
Cool, understood. 
Funnily I've got a geojson resource in catalogue.beta, and got CORS enabled both in the ini (allow all) and in the nginx conf as per CKAN docs. e.g. remote PDFs and WMS (in cesium) preview fine, whereas remote WFS show a CORS error message in cesium. Maybe I need to open the nginx config more along the lines you linked.

**Comment by florianm** [comment]
Quotes!

https://nationalmap.gov.au/proxy/_1d/http://catalogue.beta.data.wa.gov.au/api/3/action/package_search?rows=100000&fq=+(res_format:%22GeoJSON%22)

**Comment by florianm** [comment]
Update, https://nationalmap.gov.au/proxy/_1d/http://catalogue.beta.data.wa.gov.au/api/3/action/package_search?rows=100000&fq=+(groups:%22habitat-sampling-initiative%22) now works with both one and two slashes. I didn't change anything on my data.wa.gov.au side.
